### ISSUE TITLE
Failing to connect

### ISSUE THREAD

**Issue by IanMayo** [serge-web/3rd-party#2]
I'm serving the `Collab test` branch via `yarn develop`.

I'm logged into the game via this URL:
http://localhost:3000/?wargame=wargame-lw7k3gk3&access=blue-mtg-1

Here is the UI:
![image](https://github.com/serge-web/3rd-party/assets/1108513/f3f4d4ea-8f65-4057-b0db-e5586dd16f67)

I'm serving the 3rd party connector via `python app.py`, viewing via `localhost:5000`.

When I try to connect via the above URL, it fails to connect:
![image](https://github.com/serge-web/3rd-party/assets/1108513/e8afd38d-eda2-45ab-ac94-24c9f9999a9d)

Here is the response in the network tab:
![image](https://github.com/serge-web/3rd-party/assets/1108513/a2119892-180f-4d8c-b202-4ac8f81c2105)

**Comment by lilitkarapetyan** [comment]
@IanMayo We need to activate the wargame feature with lochalosr:300 (react) as well ?

**Comment by lilitkarapetyan** [comment]
It now functions properly when connecting through the server path - http://localhost:8080/?wargame=wargame-lw7k3gk3&access=blue-mtg-1
React is on different port. That's why it doesn't work with localhost: 3000.

**Comment by IanMayo** [comment]
Aah @lilitkarapetyan , is it because I was running as `yarn develop`?

**Comment by lilitkarapetyan** [comment]
Yes, it opens lochalhost:3000, wich is React development port. After copying URL, it's not the server path, it will fail. 
for local development now our server port is lochalhost: 8080.

**Comment by lilitkarapetyan** [comment]
Is UI Exploner using the React development port (lochalhost: 3000)?

**Comment by IanMayo** [comment]
Aah, I don't think I realised that `yarn develop` started two separate processes.  I understand that a little better now, thanks :-)
